: "05. The Ace of Spades accounts for what % of the total cards of a standard deck?"
1: "06. The now-abolished Wealth Tax of India last had a charge of __%"
2: "07. If a man's wife has 5 siinngs. he has married _.X of his mother-in-Iaw‘s children."
3: "01. Which of these is NOT a form of water?"
4: "02. What has eight ﬁngers. two thumbs and thirty-two teeth?"
5: "03. What name is common to a former Indian cricketer and a famous elephant?"
6: "04. What colour is represented by K in the CMYK colour model?"
7: "05. The ﬁrst use of the word "cell" in biology can be credited to which scientist?"
8: "06. If x‘2 + y‘2 = 2‘2. then which of these is correct?"
9: "07. Outside of Harry Potter, you can also become part of the Order of the Phoenix in __."
10: "08. With whom would you associate the moniker "Robin Hood of Punjab"?"
11: "09. Which of these is NOT a form of the Prakrit language?"
12: "010. Which of these is the most expensive domain name?"
